backend:
  name: git-gateway
  repo: pixleight/chrisv.dev
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - label: "Pages"
    name: "mainpages"
    files:
      - label: "Home Page"
        name: "home"
        file: "site/pages/home.md"
        fields:
          # - { label: "ID", name: "id", widget: "id" }
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Brands"
            name: "brands"
            widget: "relation"
            collection: "brands"
            multiple: true
            searchFields: ["title"]
            valueField: "title"
            displayFields: ["title"]
      - label: "About"
        name: "about"
        file: "site/pages/about.md"
        fields:
          # - { label: "ID", name: "id", widget: "id" }
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "site/pages/contact.md"
        fields:
          # - { label: "ID", name: "id", widget: "id" }
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "What I Use"
        name: "use"
        file: "site/pages/use.md"
        fields:
          # - { label: "ID", name: "id", widget: "id" }
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "snippets"
    label: "Snippets"
    folder: "site/posts/snippets"
    create: true
    slug: "{{slug}}"
    fields:
      # - { label: "ID", name: "id", widget: "uuid" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "date" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        field: {label: Name, name: name, widget: string, default: "tag"}
      - { label: "Featured Image", name: "image", widget: "image", required: true }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "work"
    label: "Work"
    folder: "site/posts/work"
    create: true
    slug: "{{slug}}"
    fields:
      # - { label: "ID", name: "id", widget: "id" }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Excerpt", name: "excerpt", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "date" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        field: {label: Name, name: name, widget: string, default: "tag"}
      - { label: "Featured Image", name: "image", widget: "image", required: true }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "articles"
    label: "Articles"
    folder: "site/posts/articles"
    create: true
    slug: "{{slug}}"
    fields:
      # - { label: "ID", name: "id", widget: "id" }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Excerpt", name: "excerpt", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "date" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        field: {label: Name, name: name, widget: string, default: "tag"}
      - { label: "Featured Image", name: "image", widget: "image", required: true }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "brands"
    label: "Brands"
    folder: "site/posts/brands"
    create: true
    slug: "{{slug}}"
    fields:
      # - { label: "ID", name: "id", widget: "id" }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Logo", name: "logo", widget: "image", required: true }
