backend:
  name: git-gateway
  repo: pixleight/chrisv.dev
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "site/pages/home.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
  - name: "snippets"
    label: "Snippets"
    folder: "site/posts/snippets"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "date"}
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        min: 1
        options: ["HTML", "CSS", "SCSS", "JavaScript", "Vue", "Craft CMS", "Twig", "WordPress", "PHP"]
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Code", name: "code", widget: "code", allow_language_selection: true}
      - {label: "Body", name: "body", widget: "markdown"}
